test0: Test passed, expected no exception thrown
test1: Test passed, expected TypeError-eval is not a constructor
Passed
